### ISSUE TITLE
comsumption by staff

### ISSUE THREAD

**Issue by cfoellmann** [jere63fr/dolibarr.consumption#3]
we have staff that get consumables like towels, paint, cleaner and so on.
We need to track our stock and see who might consume too much of an article in relation to others and/or the work that was scheduled.

So I will add the ability set a user (internal) as the target of the removal of stock.

**Comment by cfoellmann** [comment]
The code from #4 is in production at our company

**Comment by jere63fr** [comment]
ok I merged it on develop branch
